// templates/firebase-app/files-react/apps/web/src/components/Dashboard.tsx
/**
 * Dashboard Component
 *
 * Protected page showing user info and calling the authenticated API.
 */

import React, { useEffect, useState } from 'react';
import { useAuth } from '../contexts/AuthContext';
import { useNavigate } from 'react-router-dom';

interface UserProfile {
  uid: string;
  email: string;
  createdAt?: string;
}

export function Dashboard() {
  const { user, signOut, getIdToken } = useAuth();
  const navigate = useNavigate();
  const [profile, setProfile] = useState<UserProfile | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');

  useEffect(() => {
    async function fetchProfile() {
      try {
        const token = await getIdToken();
        if (!token) {
          setError('Not authenticated');
          return;
        }

        const response = await fetch('/api/profile', {
          headers: {
            Authorization: `Bearer ${token}`,
          },
        });

        if (!response.ok) {
          throw new Error('Failed to fetch profile');
        }

        const data = await response.json();
        setProfile(data);
      } catch (err) {
        setError(err instanceof Error ? err.message : 'Failed to load profile');
      } finally {
        setLoading(false);
      }
    }

    fetchProfile();
  }, [getIdToken]);

  const handleSignOut = async () => {
    await signOut();
    navigate('/login');
  };

  return (
    <div className="dashboard-container">
      <header className="dashboard-header">
        <h1>Dashboard</h1>
        <button onClick={handleSignOut} className="btn-secondary">
          Sign Out
        </button>
      </header>

      <main className="dashboard-content">
        <div className="card">
          <h2>Welcome!</h2>
          <p>You're signed in as <strong>{user?.email}</strong></p>
        </div>

        <div className="card">
          <h2>Your Profile</h2>
          {loading && <p>Loading profile...</p>}
          {error && <p className="error-message">{error}</p>}
          {profile && (
            <dl className="profile-details">
              <dt>User ID</dt>
              <dd>{profile.uid}</dd>
              <dt>Email</dt>
              <dd>{profile.email}</dd>
              {profile.createdAt && (
                <>
                  <dt>Member since</dt>
                  <dd>{new Date(profile.createdAt).toLocaleDateString()}</dd>
                </>
              )}
            </dl>
          )}
        </div>
      </main>
    </div>
  );
}

// templates/firebase-app/files-vue/apps/web/src/components/Dashboard.vue
<script setup lang="ts">
/**
 * Dashboard Component
 *
 * Protected page showing user info and calling the authenticated API.
 */

import { ref, onMounted } from 'vue';
import { useRouter } from 'vue-router';
import { useAuth } from '../composables/useAuth';

interface UserProfile {
  uid: string;
  email: string;
  createdAt?: string;
}

const profile = ref<UserProfile | null>(null);
const isLoading = ref(true);
const errorMessage = ref('');

const router = useRouter();
const { user, signOut, getIdToken } = useAuth();

const fetchProfile = async () => {
  try {
    const token = await getIdToken();
    if (!token) {
      errorMessage.value = 'Not authenticated';
      return;
    }

    const response = await fetch('/api/profile', {
      headers: {
        Authorization: `Bearer ${token}`,
      },
    });

    if (!response.ok) {
      throw new Error('Failed to fetch profile');
    }

    profile.value = await response.json();
  } catch (err) {
    errorMessage.value = err instanceof Error ? err.message : 'Failed to load profile';
  } finally {
    isLoading.value = false;
  }
};

const handleSignOut = async () => {
  await signOut();
  router.push('/login');
};

onMounted(() => {
  fetchProfile();
});
</script>

<template>
  <div class="dashboard-container">
    <header class="dashboard-header">
      <h1>Dashboard</h1>
      <button @click="handleSignOut" class="btn-secondary">
        Sign Out
      </button>
    </header>

    <main class="dashboard-content">
      <div class="card">
        <h2>Welcome!</h2>
        <p>You're signed in as <strong>{{ user?.email }}</strong></p>
      </div>

      <div class="card">
        <h2>Your Profile</h2>
        <p v-if="isLoading">Loading profile...</p>
        <p v-else-if="errorMessage" class="error-message">{{ errorMessage }}</p>
        <dl v-else-if="profile" class="profile-details">
          <dt>User ID</dt>
          <dd>{{ profile.uid }}</dd>
          <dt>Email</dt>
          <dd>{{ profile.email }}</dd>
          <template v-if="profile.createdAt">
            <dt>Member since</dt>
            <dd>{{ new Date(profile.createdAt).toLocaleDateString() }}</dd>
          </template>
        </dl>
      </div>
    </main>
  </div>
</template>
